development:
  adapter: postgresql
  database: smart_db_develop
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: smart_db_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: smart_db_production
  pool: 5
  timeout: 5000
